name: Sphinx Docs

on:
  push:
    branches: [main]  # or 'master' depending on your default branch
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # important for gh-pages push

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # or any version you support

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx furo  # or whatever theme you're using
        pip install -r requirements.txt  # if you have extra requirements

    - name: Build documentation
      run: |
        cd docs
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
